### ISSUE TITLE
Can't push to GitHub: error: index-pack died of signal 11

### ISSUE THREAD

**Issue by AlainODea** [schacon/hg-git#216]
When I try to push to GitHub I get an error message `error: index-pack died of signal 11`.  Here is a transcript:

```
$ hg --debug push git+ssh://git@github.com/zotonic/zotonic-test
pushing to git+ssh://git@github.com/zotonic/zotonic-test
creating and sending data
calling ssh: ssh git@github.com 'git-receive-pack '\''/zotonic/zotonic-test'\'''
["git-receive-pack '/zotonic/zotonic-test'"]
error: index-pack died of signal 11
broken pipe
```

This happens on both my laptop and the server from which I attempting to synchronize the Mercurial and Git repositories.

**Comment by bngsudheer** [comment]
python-dulwich 0.9.7
latest hg-git from Github

Can't push to git repo. I get the error: 
hg --debug push github
pushing to git+ssh://git@github.com:bngsudheer/Flask-Webhelpers.git
calling ssh: ssh git@github.com 'git-receive-pack '\''bngsudheer/Flask-Webhelpers.git'\'''
searching for changes
1 commits found
list of commits:
7c6a787dce7b381dbafbb4b9df024a4ff10ef7f3
adding objects
abort: git remote error: unpack index-pack abnormal exit

**Comment by Zogg** [comment]
Experiencing same error as @bngsudheer .

**Comment by bngsudheer** [comment]
I figured out my problem. I had a '.git' directory in my Mercurial repository. Mercurial itself has not problem having a directory by name '.git'. However, github.com will not accept pushes if the repository contains a '.git' directory. hg-git has nothing to do with it, I guess. 

My solution was to remove the offending directory from the Mercurial repository and its history.

**Comment by Zogg** [comment]
@bngsudheer Indeed, I also  have .git directory in my repo history. Do you have any guidelines how to safely remove .git from (mercurial) repository history?

**Comment by bngsudheer** [comment]
Zogg, sorry, no. I wiped all the history(started a new repository).

**Comment by Zogg** [comment]
https://www.jitbit.com/alexblog/232-removing-files-from-mercurial-history/ is how to safely remove files from the history. Thanks for a tip, @bngsudheer , that solved the problem.

**Comment by stvenyin** [comment]
i.don't know
